version: '3.4'

services:
  bookshop.bookservice.rpc:
    image: ${DOCKER_REGISTRY-}bookshop.bookservice
    container_name: bookshop.bookservice
    networks:
    - bookshopnetwork
    - elasticsearchnetwork
    build:
      context: .
      dockerfile: BookShop.BookService.Rpc/Dockerfile
    environment:
        Elasticsearch__Url: http://elastic:9200

  bookshop.getway.rest:
    image: ${DOCKER_REGISTRY-}bookshop.getway
    container_name: bookshop.getway
    networks:
    - bookshopnetwork
    - redisnetwork
    build:
      context: .
      dockerfile: BookShop.Getway.Rest/Dockerfile
    environment:
        Redis__Url: redis
        ExternalService__BookService__Url: https://bookshop.bookservice
        ExternalService__BookService__CacheTimeInSeconds: 5
  redis:
    image: redis
    container_name: redis
    networks:
    - redisnetwork

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elastic
    environment:
        - node.name=elastic
        - discovery.type=single-node
    ports:
        - "9200:9200"
        - "9300:9300"
    volumes:
        - type: bind
          source: ./elasticsearchdata
          target: /usr/share/elasticsearch/data
    networks:
        - elasticsearchnetwork
  kibana:
        image: docker.elastic.co/kibana/kibana:7.10.1
        container_name: kibana
        ports:
            - "5601:5601"
        networks:
            - elasticsearchnetwork
        depends_on:
            - elasticsearch
volumes:
    elasticsearchdata:

networks:
  bookshopnetwork:
    driver: bridge
  redisnetwork:
    driver: bridge
  elasticsearchnetwork:
    driver: bridge
